# Generated by Django 5.1.6 on 2025-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('orbital_state', models.CharField(max_length=50, verbose_name='Estado Orbital')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('orbit', models.CharField(max_length=50, verbose_name='Órbita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Satélite',
                'ordering': ['name'],
            },
        ),
    ]
